title: "Teaching Robots how to Drum"
description: "Experiments in making music by atrodo"
show_downloads: false
theme: jekyll-theme-midnight
baseurl:
google_analytics: G-CEN8CCMRWE
url: "https://atrodo.github.io"
plugins:
  - jekyll-sitemap
